// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWiueQ7dS2K5FKumTyYUUQTnumf6XYRk',
    appId: '1:125288735086:web:348f9a68a2f2e06392617f',
    messagingSenderId: '125288735086',
    projectId: 'crel-site',
    authDomain: 'crel-site.firebaseapp.com',
    storageBucket: 'crel-site.appspot.com',
    measurementId: 'G-B0XYDDNDTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnH8ATc5cakmqlhZaEgNakThFgjCa4894',
    appId: '1:125288735086:android:291feee1716a6e4f92617f',
    messagingSenderId: '125288735086',
    projectId: 'crel-site',
    storageBucket: 'crel-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEtF_SHtvgAWIibHCRyuqqMDsuZOmI40',
    appId: '1:125288735086:ios:efe683cf1fe5dc5e92617f',
    messagingSenderId: '125288735086',
    projectId: 'crel-site',
    storageBucket: 'crel-site.appspot.com',
    androidClientId: '125288735086-2nbr9n53eeq6ptpp3ohvmghv8aeqcgtr.apps.googleusercontent.com',
    iosClientId: '125288735086-s0jhe79a5dbg2s7n60iargfcb84cdu3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.crelMobile',
  );
}
